org: emma50
app: aws-node-project
service: aws-node-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello-short-timeout:
    handler: handler.hello
    timeout: 5
    memorySize: 128
  hello-long-timeout:
    handler: handler.hello
    timeout: 10
    memorySize: 256
