org: emma50
app: aws-node-project
service: aws-node-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello-short-timeout:
    handler: handler.hello
    timeout: 3
    memorySize: 128
    description: short timeout function
  hello-long-timeout:
    handler: handler.hello
    timeout: 7
    memorySize: 256
    description: Long timeout function
