org: emma50
app: aws-node-project
service: aws-node-project

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  # This will be overriden if props is set on the function name
  timeout: 2
  memorySize: 512
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lamda:*"
          Resource:
            - "*"
  environment:
    FIRSTNAME: ${env:FIRST_NAME}

functions:
  hello-short-timeout: # function nane
    handler: handler.hello
    description: short timeout function
  hello-long-timeout: # function nane
    handler: handler.hello
    timeout: 7
    memorySize: 256
    description: Long timeout function

package:
  # Exclude the deployment of files (i.e node_modules) to AWS
  exclude:
    - node_modules/**
